### ISSUE TITLE
[feature]: Tag source type

### ISSUE THREAD

**Issue by imeed166** [tomaszkiewicz/obsidian-database-plugin#1]
Like dataview, it would be nice to query files based on tags as not all of as use folders.

**Comment by javiavid** [comment]
+1

**Comment by tomaszkiewicz** [comment]
I did some research and... it seems Dataview exposes API that other plugins can use. I'm considering implementing Dataview queries as a type of source for my plugin - this way it'll be very easy to migrate existing Dataview tables and it'll also save some code on filtering :)

**Comment by tomaszkiewicz** [comment]
I implemented `tags` source and `related` source, both allow filtering by tags, so I'm closing this one.
