### ISSUE TITLE
Ignore subfolder and file extension

### ISSUE THREAD

**Issue by javiavid** [tomaszkiewicz/obsidian-database-plugin#6]
If you create a folder to make a database of people or products, it is normal that you have images.
I have the images in a subfolder called images.

When viewing the database, the md notes and images are shown and it is a bit confusing.

An option to ignore subfolders or some extensions would be nice.

**Comment by tomaszkiewicz** [comment]
Ignoring non-md files will be avaiable with next release - it's in the code already, but I need to work on some process for auto-releasing new versions as it's time-consuming to do it manually after each commit ;)

**Comment by javiavid** [comment]
Thanks

**Comment by tomaszkiewicz** [comment]
Fixed in 1.0.3 release :)
