### ISSUE TITLE
[Bug]: plugin css affect checkboxes

### ISSUE THREAD

**Issue by imeed166** [tomaszkiewicz/obsidian-database-plugin#7]
the checkboxes appear flat when enabling the plugin while using custom theme (like [shimmering focus](https://github.com/chrisgrieser/shimmering-focus/issues/159)).

https://user-images.githubusercontent.com/38974541/166682489-c57b30a4-c49e-46a1-b778-238fbf022c80.mov

**Comment by tomaszkiewicz** [comment]
How can I reproduce that error? Do you mean any specific custom theme?

**Comment by imeed166** [comment]
in the default theme, nothing's wrong. But when I switched to other themes (like its, minimal, shimmering focus, sanctum, primary) all of them have the same problem.

**Comment by tomaszkiewicz** [comment]
Ok, I probably found the issue, but I have to test it a little more and implement a workaround.

**Comment by tomaszkiewicz** [comment]
Ok, fixed in new release.
