### ISSUE TITLE
[feature] support for BRAT plugin

### ISSUE THREAD

**Issue by imeed166** [tomaszkiewicz/obsidian-database-plugin#8]
It would be nice if we could use [BRAT](https://github.com/TfTHacker/obsidian42-brat) to install and/or update this plugin, instead of doing it manually.

For now, this is what I get when I try installing with BRAT :

![image](https://user-images.githubusercontent.com/38974541/167304171-2c8e87af-3bc2-47fd-99a6-a8198e7b324f.png)

**Comment by tomaszkiewicz** [comment]
It works on my machine, I think you need to provide URL to a repository, not to issues page, in my case:

https://github.com/tomaszkiewicz/obsidian-database-plugin

**Comment by imeed166** [comment]
Ah sorry, my mistake.
