### ISSUE TITLE
Create new row directly within the database table

### ISSUE THREAD

**Issue by crazymedguy** [tomaszkiewicz/obsidian-database-plugin#9]
Not sure if this is planned, but being able to create a new file/row directly within the database table would make this really powerful. Also, the ability to move delete rows/files too.

**Comment by tomaszkiewicz** [comment]
That feature is definitely on my roadmap, however I have to design a consistent way to do so - it's quite easy with `directory` source, a little bit trickier with `tags` source (as the content may be overwritten by other plugin like Templater) and quite a challenge for `related` source (how to link that back to the page? Where to put the link?)

Deleting file on the other hand is quite easy and it will be implemented it in on of the next versions.

**Comment by tomaszkiewicz** [comment]
Check 1.8.0 version - I've added support for deleting and adding files :)
